[alembic]
# Path to migration scripts
script_location = alembic

# Template used to generate migration file names; The default value is %%(rev)s_%%(slug)s
# Uncomment the line below if you want the files to be prepended with date and time
# see https://alembic.sqlalchemy.org/en/latest/tutorial.html#editing-the-ini-file
# for all available tokens
file_template = %%(year)d_%%(month).2d_%%(day).2d_%%(hour).2d%%(minute).2d_%%(rev)s_%%(slug)s

# sys.path path, will be prepended to sys.path if present.
# defaults to the current working directory.
prepend_sys_path = .

# timezone to use when rendering the date within the migration file
# as well as the filename.
# If specified, requires the python-dateutil library that can be
# installed by adding `alembic[tz]` to the pip requirements
# string value is passed to dateutil.tz.gettz()
# leave blank for localtime
# timezone =

# max length of characters to apply to the
# "slug" field
# max_length = 40

# version_num (SQLAlchemy 1.4.0 and above)
# version_num determines if the version_num column in the alembic_version table
# should be populated with the version of the revision during an upgrade vs.
# populating with a null value. Setting to False maintains backwards compatibility
# with SQLAlchemy versions prior to 1.4.0.
version_num = true

# format of the revision file output
# Can be one of 'literal', 'string', 'repr', 'json', 'yaml'
# If not specified, 'literal' is used for backwards compatibility
# revision_environment = false

# version_locations allows for multiple version locations
# version_locations = %(here)s/bar:%(here)s/bat:alembic/versions

# Logging configuration
[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S