"""add_automation_tables

Revision ID: 130c7854c091
Revises: 
Create Date: 2025-11-29 10:45:11.367968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '130c7854c091'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('automation_triggers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('trigger_event_type', sa.String(length=50), nullable=False),
    sa.Column('fragment_key', sa.String(length=50), nullable=True),
    sa.Column('mission_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('points_threshold', sa.Integer(), nullable=True),
    sa.Column('level_threshold', sa.Integer(), nullable=True),
    sa.Column('conditions', sa.JSON(), nullable=True),
    sa.Column('total_activations', sa.Integer(), nullable=False),
    sa.Column('last_activated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_automation_triggers_enabled'), 'automation_triggers', ['enabled'], unique=False)
    op.create_index(op.f('ix_automation_triggers_fragment_key'), 'automation_triggers', ['fragment_key'], unique=False)
    op.create_index(op.f('ix_automation_triggers_mission_id'), 'automation_triggers', ['mission_id'], unique=False)
    op.create_index(op.f('ix_automation_triggers_name'), 'automation_triggers', ['name'], unique=True)
    op.create_index(op.f('ix_automation_triggers_product_id'), 'automation_triggers', ['product_id'], unique=False)
    op.create_index(op.f('ix_automation_triggers_trigger_event_type'), 'automation_triggers', ['trigger_event_type'], unique=False)
    op.create_table('trigger_actions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trigger_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('fragment_key', sa.String(length=50), nullable=True),
    sa.Column('lore_piece_id', sa.Integer(), nullable=True),
    sa.Column('mission_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('role_name', sa.String(length=50), nullable=True),
    sa.Column('group_id', sa.String(length=50), nullable=True),
    sa.Column('message_template', sa.Text(), nullable=True),
    sa.Column('execution_order', sa.Integer(), nullable=False),
    sa.Column('action_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['trigger_id'], ['automation_triggers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trigger_actions_fragment_key'), 'trigger_actions', ['fragment_key'], unique=False)
    op.create_index(op.f('ix_trigger_actions_lore_piece_id'), 'trigger_actions', ['lore_piece_id'], unique=False)
    op.create_index(op.f('ix_trigger_actions_mission_id'), 'trigger_actions', ['mission_id'], unique=False)
    op.create_index(op.f('ix_trigger_actions_product_id'), 'trigger_actions', ['product_id'], unique=False)
    op.create_index(op.f('ix_trigger_actions_trigger_id'), 'trigger_actions', ['trigger_id'], unique=False)
    op.create_table('trigger_execution_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trigger_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('actions_executed', sa.Integer(), nullable=False),
    sa.Column('execution_time_ms', sa.Integer(), nullable=True),
    sa.Column('context', sa.JSON(), nullable=True),
    sa.Column('executed_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['trigger_id'], ['automation_triggers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trigger_execution_logs_executed_at'), 'trigger_execution_logs', ['executed_at'], unique=False)
    op.create_index(op.f('ix_trigger_execution_logs_trigger_id'), 'trigger_execution_logs', ['trigger_id'], unique=False)
    op.create_index(op.f('ix_trigger_execution_logs_user_id'), 'trigger_execution_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trigger_execution_logs_user_id'), table_name='trigger_execution_logs')
    op.drop_index(op.f('ix_trigger_execution_logs_trigger_id'), table_name='trigger_execution_logs')
    op.drop_index(op.f('ix_trigger_execution_logs_executed_at'), table_name='trigger_execution_logs')
    op.drop_table('trigger_execution_logs')
    op.drop_index(op.f('ix_trigger_actions_trigger_id'), table_name='trigger_actions')
    op.drop_index(op.f('ix_trigger_actions_product_id'), table_name='trigger_actions')
    op.drop_index(op.f('ix_trigger_actions_mission_id'), table_name='trigger_actions')
    op.drop_index(op.f('ix_trigger_actions_lore_piece_id'), table_name='trigger_actions')
    op.drop_index(op.f('ix_trigger_actions_fragment_key'), table_name='trigger_actions')
    op.drop_table('trigger_actions')
    op.drop_index(op.f('ix_automation_triggers_trigger_event_type'), table_name='automation_triggers')
    op.drop_index(op.f('ix_automation_triggers_product_id'), table_name='automation_triggers')
    op.drop_index(op.f('ix_automation_triggers_name'), table_name='automation_triggers')
    op.drop_index(op.f('ix_automation_triggers_mission_id'), table_name='automation_triggers')
    op.drop_index(op.f('ix_automation_triggers_fragment_key'), table_name='automation_triggers')
    op.drop_index(op.f('ix_automation_triggers_enabled'), table_name='automation_triggers')
    op.drop_table('automation_triggers')
    # ### end Alembic commands ###
