"""Initial revision of all models

Revision ID: 9e6fe9934bf5
Revises: 
Create Date: 2025-11-25 18:44:45.481138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e6fe9934bf5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievements',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('condition_type', sa.String(), nullable=False),
    sa.Column('condition_value', sa.Integer(), nullable=False),
    sa.Column('reward_text', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('badges',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('condition_type', sa.String(), nullable=False),
    sa.Column('condition_value', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('bot_config',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('free_channel_wait_time_minutes', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('channels',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('reactions', sa.JSON(), nullable=True),
    sa.Column('reaction_points', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('challenges',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('goal_type', sa.String(), nullable=False),
    sa.Column('goal_value', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('compatibility_quizzes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('besitos_reward', sa.Integer(), nullable=False),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('average_completion_time', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('config_entries',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('content_sets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('tier', sa.String(), nullable=False),
    sa.Column('file_ids', sa.JSON(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('for_archetype', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('multiplier', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('levels',
    sa.Column('level_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('min_points', sa.Integer(), nullable=False),
    sa.Column('reward', sa.String(), nullable=True),
    sa.Column('unlocks_lore_piece_code', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('level_id')
    )
    op.create_table('pending_channel_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('request_timestamp', sa.DateTime(), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('raffles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('prize', sa.String(), nullable=True),
    sa.Column('winner_id', sa.BigInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rewards',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('required_points', sa.Integer(), nullable=False),
    sa.Column('reward_type', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('vip_days', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('story_fragments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('character', sa.String(length=50), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('min_besitos', sa.Integer(), nullable=True),
    sa.Column('required_role', sa.String(), nullable=True),
    sa.Column('reward_besitos', sa.Integer(), nullable=True),
    sa.Column('unlocks_achievement_id', sa.String(), nullable=True),
    sa.Column('auto_next_fragment_key', sa.String(length=50), nullable=True),
    sa.Column('archetype_variant', sa.String(length=20), nullable=True),
    sa.Column('fragment_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['unlocks_achievement_id'], ['achievements.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_index(op.f('ix_story_fragments_archetype_variant'), 'story_fragments', ['archetype_variant'], unique=False)
    op.create_index(op.f('ix_story_fragments_required_role'), 'story_fragments', ['required_role'], unique=False)
    op.create_index(op.f('ix_story_fragments_unlocks_achievement_id'), 'story_fragments', ['unlocks_achievement_id'], unique=False)
    op.create_table('subscription_plans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('used_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('tariffs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('duration_days', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('trivias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('reward_points', sa.Integer(), nullable=True),
    sa.Column('unlocks_lore_piece_code', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('points', sa.Float(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('achievements', sa.JSON(), nullable=True),
    sa.Column('missions_completed', sa.JSON(), nullable=True),
    sa.Column('last_daily_mission_reset', sa.DateTime(), nullable=True),
    sa.Column('last_weekly_mission_reset', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('vip_expires_at', sa.DateTime(), nullable=True),
    sa.Column('last_reminder_sent_at', sa.DateTime(), nullable=True),
    sa.Column('menu_state', sa.String(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('auctions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('prize_description', sa.Text(), nullable=False),
    sa.Column('initial_price', sa.Integer(), nullable=False),
    sa.Column('current_highest_bid', sa.Integer(), nullable=True),
    sa.Column('highest_bidder_id', sa.BigInteger(), nullable=True),
    sa.Column('winner_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'ENDED', 'CANCELLED', name='auctionstatus'), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('min_bid_increment', sa.Integer(), nullable=True),
    sa.Column('max_participants', sa.Integer(), nullable=True),
    sa.Column('auto_extend_minutes', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['highest_bidder_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['winner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('button_reactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('reaction_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gift_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('content_set_id', sa.String(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('context', sa.String(), nullable=True),
    sa.Column('trigger_type', sa.String(), nullable=True),
    sa.Column('sent_by_admin', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['content_set_id'], ['content_sets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invite_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('used_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('lore_pieces',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code_name', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('content_type', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('is_main_story', sa.Boolean(), nullable=True),
    sa.Column('unlock_condition_type', sa.String(), nullable=True),
    sa.Column('unlock_condition_value', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code_name')
    )
    op.create_table('minigame_play',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('game_type', sa.String(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('is_free', sa.Boolean(), nullable=True),
    sa.Column('cost_points', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('missions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('reward_points', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('target_value', sa.Integer(), nullable=True),
    sa.Column('duration_days', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('requires_action', sa.Boolean(), nullable=True),
    sa.Column('action_data', sa.JSON(), nullable=True),
    sa.Column('unlocks_lore_piece_code', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('mission_category', sa.String(), nullable=True),
    sa.Column('is_hidden', sa.Boolean(), nullable=True),
    sa.Column('icon_emoji', sa.String(), nullable=True),
    sa.Column('difficulty_level', sa.Integer(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('prerequisite_mission_id', sa.String(), nullable=True),
    sa.Column('unlocks_mission_id', sa.String(), nullable=True),
    sa.Column('time_limit_minutes', sa.Integer(), nullable=True),
    sa.Column('bonus_points_if_fast', sa.Integer(), nullable=True),
    sa.Column('min_ranking_position', sa.Integer(), nullable=True),
    sa.Column('max_completions_global', sa.Integer(), nullable=True),
    sa.Column('current_completions_global', sa.Integer(), nullable=True),
    sa.Column('repeatable', sa.Boolean(), nullable=True),
    sa.Column('reset_period', sa.String(), nullable=True),
    sa.Column('xp_reward', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['prerequisite_mission_id'], ['missions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['unlocks_lore_piece_code'], ['lore_pieces.code_name'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['unlocks_mission_id'], ['missions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_missions_unlocks_lore_piece_code'), 'missions', ['unlocks_lore_piece_code'], unique=False)
    op.create_table('narrative_choices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_fragment_id', sa.Integer(), nullable=False),
    sa.Column('destination_fragment_key', sa.String(length=50), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('required_besitos', sa.Integer(), nullable=True),
    sa.Column('required_role', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['source_fragment_id'], ['story_fragments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quiz_questions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('question_number', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['quiz_id'], ['compatibility_quizzes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('raffle_entries',
    sa.Column('raffle_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['raffle_id'], ['raffles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('raffle_id', 'user_id')
    )
    op.create_table('shop_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('is_vip_only', sa.Boolean(), nullable=True),
    sa.Column('unlocks_lore_piece_id', sa.Integer(), nullable=True),
    sa.Column('unlocks_fragment_key', sa.String(length=50), nullable=True),
    sa.Column('image_file_id', sa.String(length=255), nullable=True),
    sa.Column('stock_limit', sa.Integer(), nullable=True),
    sa.Column('max_purchases_per_user', sa.Integer(), nullable=True),
    sa.Column('available_from', sa.DateTime(), nullable=True),
    sa.Column('available_until', sa.DateTime(), nullable=True),
    sa.Column('unlock_requirements', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['unlocks_lore_piece_id'], ['lore_pieces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscription_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('used_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('tokens',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('token_string', sa.String(), nullable=True),
    sa.Column('tariff_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('activated_at', sa.DateTime(), nullable=True),
    sa.Column('is_used', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['tariff_id'], ['tariffs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_string')
    )
    op.create_table('trivia_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trivia_id', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('question_type', sa.Enum('multiple_choice', 'open_ended', 'visual', name='question_types'), nullable=True),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('correct_answer', sa.String(), nullable=False),
    sa.Column('media_type', sa.String(), nullable=True),
    sa.Column('media_path', sa.String(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['trivia_id'], ['trivias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_achievements',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('achievement_id', sa.String(), nullable=False),
    sa.Column('unlocked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['achievement_id'], ['achievements.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'achievement_id'),
    sa.UniqueConstraint('user_id', 'achievement_id', name='uix_user_achievements')
    )
    op.create_table('user_badges',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('badge_id', sa.Integer(), nullable=False),
    sa.Column('awarded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['badge_id'], ['badges.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'badge_id', name='uix_user_badges')
    )
    op.create_table('user_challenge_progress',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('challenge_id', sa.Integer(), nullable=False),
    sa.Column('current_value', sa.Integer(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'challenge_id')
    )
    op.create_table('user_milestones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('milestone_type', sa.String(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'milestone_type', name='uix_user_milestone')
    )
    op.create_table('user_mission_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('mission_id', sa.String(), nullable=True),
    sa.Column('progress_value', sa.Integer(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'mission_id', name='uix_user_mission_entry')
    )
    op.create_table('user_narrative_states',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('current_fragment_key', sa.String(length=50), nullable=True),
    sa.Column('choices_made', sa.JSON(), nullable=True),
    sa.Column('fragments_visited', sa.Integer(), nullable=True),
    sa.Column('total_besitos_earned', sa.Integer(), nullable=True),
    sa.Column('narrative_started_at', sa.DateTime(), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(), nullable=True),
    sa.Column('shop_redirect_fragment_key', sa.String(length=50), nullable=True),
    sa.Column('pending_decision_id', sa.Integer(), nullable=True),
    sa.Column('unlocked_fragments', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('user_rewards',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('reward_id', sa.Integer(), nullable=False),
    sa.Column('claimed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['reward_id'], ['rewards.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'reward_id')
    )
    op.create_table('user_stats',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(), nullable=True),
    sa.Column('last_checkin_at', sa.DateTime(), nullable=True),
    sa.Column('last_daily_gift_at', sa.DateTime(), nullable=True),
    sa.Column('last_notified_points', sa.Float(), nullable=True),
    sa.Column('messages_sent', sa.Integer(), nullable=True),
    sa.Column('checkin_streak', sa.Integer(), nullable=True),
    sa.Column('last_roulette_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('vip_grants',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('days_granted', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('granted_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('invite_link', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vip_subscriptions',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('auction_participants',
    sa.Column('auction_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.Column('notifications_enabled', sa.Boolean(), nullable=True),
    sa.Column('last_notified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['auction_id'], ['auctions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('auction_id', 'user_id')
    )
    op.create_table('bids',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('auction_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('is_winning', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['auction_id'], ['auctions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('auction_id', 'user_id', 'amount', name='uix_auction_user_bid')
    )
    op.create_table('product_files',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('shop_item_id', sa.Integer(), nullable=False),
    sa.Column('file_type', sa.String(length=20), nullable=False),
    sa.Column('file_id', sa.String(length=255), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['shop_item_id'], ['shop_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quiz_options',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('option_number', sa.Integer(), nullable=False),
    sa.Column('option_text', sa.Text(), nullable=False),
    sa.Column('compatibility_score', sa.Integer(), nullable=False),
    sa.Column('diana_response', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['quiz_questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trivia_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('trivia_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['trivia_id'], ['trivias.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_lore_pieces',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('lore_piece_id', sa.Integer(), nullable=False),
    sa.Column('unlocked_at', sa.DateTime(), nullable=True),
    sa.Column('context', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['lore_piece_id'], ['lore_pieces.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'lore_piece_id'),
    sa.UniqueConstraint('user_id', 'lore_piece_id', name='uix_user_lore_pieces')
    )
    op.create_table('user_purchases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('shop_item_id', sa.Integer(), nullable=False),
    sa.Column('purchased_at', sa.DateTime(), nullable=True),
    sa.Column('price_paid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['shop_item_id'], ['shop_items.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trivia_user_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attempt_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('user_answer', sa.Text(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['attempt_id'], ['trivia_attempts.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['trivia_questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trivia_user_answers')
    op.drop_table('user_purchases')
    op.drop_table('user_lore_pieces')
    op.drop_table('trivia_attempts')
    op.drop_table('quiz_options')
    op.drop_table('product_files')
    op.drop_table('bids')
    op.drop_table('auction_participants')
    op.drop_table('vip_subscriptions')
    op.drop_table('vip_grants')
    op.drop_table('user_stats')
    op.drop_table('user_rewards')
    op.drop_table('user_narrative_states')
    op.drop_table('user_mission_entries')
    op.drop_table('user_milestones')
    op.drop_table('user_challenge_progress')
    op.drop_table('user_badges')
    op.drop_table('user_achievements')
    op.drop_table('trivia_questions')
    op.drop_table('tokens')
    op.drop_table('subscription_tokens')
    op.drop_table('shop_items')
    op.drop_table('raffle_entries')
    op.drop_table('quiz_questions')
    op.drop_table('narrative_choices')
    op.drop_index(op.f('ix_missions_unlocks_lore_piece_code'), table_name='missions')
    op.drop_table('missions')
    op.drop_table('minigame_play')
    op.drop_table('lore_pieces')
    op.drop_table('invite_tokens')
    op.drop_table('gift_records')
    op.drop_table('button_reactions')
    op.drop_table('auctions')
    op.drop_table('users')
    op.drop_table('trivias')
    op.drop_table('tariffs')
    op.drop_table('subscription_plans')
    op.drop_index(op.f('ix_story_fragments_unlocks_achievement_id'), table_name='story_fragments')
    op.drop_index(op.f('ix_story_fragments_required_role'), table_name='story_fragments')
    op.drop_index(op.f('ix_story_fragments_archetype_variant'), table_name='story_fragments')
    op.drop_table('story_fragments')
    op.drop_table('rewards')
    op.drop_table('raffles')
    op.drop_table('pending_channel_requests')
    op.drop_table('levels')
    op.drop_table('events')
    op.drop_table('content_sets')
    op.drop_table('config_entries')
    op.drop_table('compatibility_quizzes')
    op.drop_table('challenges')
    op.drop_table('channels')
    op.drop_table('bot_config')
    op.drop_table('badges')
    op.drop_table('achievements')
    # ### end Alembic commands ###